FROM nvcr.io/nvidia/deepstream:6.1.1-samples

# To get video driver libraries at runtime (libnvidia-encode.so/libnvcuvid.so)
ENV NVIDIA_DRIVER_CAPABILITIES $NVIDIA_DRIVER_CAPABILITIES,compute,utility,video,compute,graphics,utility

# Install required packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget python3 python3-pip python3.8-venv python-is-python3 python3-dev \
    libcairo2-dev libjpeg-dev libgif.dev \
    libssl1.1 \
    libgstreamer1.0-0 \
    gstreamer1.0-tools \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libgstreamer-plugins-base1.0-dev \
    libgstrtspserver-1.0-0 \
    libjansson4 \
    libyaml-cpp-dev \
    gcc \
    make \
    git && \
    python3 -m pip install --upgrade build && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y

# Install DeepStream Python bindings
RUN wget https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.4/pyds-1.1.4-py3-none-linux_x86_64.whl && \
    pip3 install ./pyds-1.1.4-py3-none-linux_x86_64.whl && \
    rm pyds-1.1.4-py3-none-linux_x86_64.whl

# Install the helper-package
RUN git clone https://github.com/JarnoRalli/gstreamer-examples.git && \
    cd gstreamer-examples/helper-package && \
    python3 -m build &&\
    cd dist &&\
    pip3 install $(ls | grep helpers-*.whl) &&\
    cd ../../.. &&\
    rm -rf gstreamer-examples

