services:
  rtsp_server:
    build: ./
    container_name: rtsp-server
    command: python3 /home/rtsp-server.py --files file:///Videos/${VIDEO_FILE:-default.mp4}
    volumes:
      - ${HOME}/Videos:/Videos
    network_mode: host
